
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app/src
    command: python main.py
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: seleniarm/standalone-chromium:latest
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - ./selenium:/selenium
    ports:
      - 7900:7900
    expose:
      - 4444
    environment:
      SE_NODE_SESSION_TIMEOUT: 999999999
      SE_NODE_MAX_SESSIONS: 2
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/selenium/healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "autoheal=true"

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    